version: 2.1
jobs:
  build:
    docker:
      - image: cimg/php:8.2-browsers
    steps:
      - checkout
      - run: sudo composer self-update --2
      - restore_cache:
          key: composer-v1-{{ checksum "composer.lock" }}
      - run: composer install -n --prefer-dist
      - save_cache:
          key: composer-v1-{{ checksum "composer.lock" }}
          paths:
            - vendor
      - run: npm ci
      - run: LARAVEL_BYPASS_ENV_CHECK=1 npm run build
      - run:
          name: php test
          command: vendor/bin/phpunit
